#ifndef ELEGOO_DRIVE_HTML_H
#define ELEGOO_DRIVE_HTML_H

// Single-page drive UI: MJPEG on port (camera_port+1), commands POST to /elegoo_cmd on this port.
static const char ELEGOO_DRIVE_HTML[] =
    "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>ELEGOO drive</title>"
    "<style>"
    "body{font-family:system-ui,sans-serif;margin:0;padding:8px;background:#111;color:#eee;}"
    "#wrap{max-width:640px;margin:0 auto;}"
    "#cam{width:100%;background:#000;min-height:200px;object-fit:contain;}"
    ".row{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin:12px 0;}"
    "button{min-width:88px;min-height:44px;font-size:16px;cursor:pointer;border-radius:8px;border:1px solid #444;background:#222;color:#eee;}"
    "button:active{background:#444;}"
    "#stop{background:#622;}"
    "#status{font-size:12px;color:#888;margin-top:8px;word-break:break-all;}"
    "</style></head><body><div id=\"wrap\">"
    "<h2 style=\"margin:8px 0;font-size:1.1rem;\">Camera + drive</h2>"
    "<p style=\"margin:0 0 12px;font-size:13px;\"><a href=\"/\" style=\"color:#8cf;\">Full ESP camera UI (sidebar)</a></p>"
    "<img id=\"cam\" alt=\"stream\"/>"
    "<div class=\"row\">"
    "<button type=\"button\" id=\"stop\">Stop</button>"
    "</div>"
    "<div class=\"row\" style=\"flex-direction:column;align-items:center;\">"
    "<button type=\"button\" id=\"fwd\">Forward</button>"
    "<div class=\"row\" style=\"margin:0;\">"
    "<button type=\"button\" id=\"left\">Left</button>"
    "<button type=\"button\" id=\"right\">Right</button>"
    "</div>"
    "<button type=\"button\" id=\"back\">Back</button>"
    "</div>"
    "<p id=\"status\"></p>"
    "</div>"
    "<script>"
    "(function(){"
    "var cam=document.getElementById('cam');"
    "var st=document.getElementById('status');"
    "cam.src=window.location.origin+'/stream';"
    "function log(m){st.textContent=m;}"
    "function sendJson(body){"
    "log('Sending…');"
    "return fetch('/elegoo_cmd',{method:'POST',headers:{'Content-Type':'application/json'},body:body})"
    ".then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();})"
    ".then(function(){log('OK '+new Date().toISOString());})"
    ".catch(function(e){log('Error: '+e);});"
    "}"
    "function carUntimed(d1){"
    "var H='web_'+Date.now()+'_0';"
    "return sendJson(JSON.stringify({N:3,D1:d1,D2:80,H:H}));"
    "}"
    "document.getElementById('stop').onclick=function(){sendJson('{\"N\":100}');};"
    "document.getElementById('fwd').onclick=function(){carUntimed(3);};"
    "document.getElementById('back').onclick=function(){carUntimed(4);};"
    "document.getElementById('left').onclick=function(){carUntimed(1);};"
    "document.getElementById('right').onclick=function(){carUntimed(2);};"
    "})();"
    "</script></body></html>";

#endif
